src/org/urls.py
from django.urls import path
from org.views import (
	create_org_view,
	detail_org_view,
	edit_org_view,
)

app_name = 'org'

urlpatterns = [
    path('create/', create_org_view, name="create"),
    path('<slug>/', detail_org_view, name="detail"),
    path('<slug>/edit/', edit_org_view, name="edit"),
 ]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from post.views import (
	home_view,
)

from home.views import (
    registration_view,
    logout_view,
    login_view,
	
)

urlpatterns = [
    path('', home_view, name="home"),
    path('org/', include('org.urls', 'org')),
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>

<!-- Body -->
<style type="text/css">
	.main{
		min-height: 100vh;
		height: 100%;
	}
</style>
<div class="main">
    <style type="text/css">
        @media (min-width: 768px) {
          html {
            font-size: 16px;
          }
        }
    
        .search-bar{
            max-width: 500px;
            width: 100%;
        }
        form{
            width: 100%;
        }
    </style>
    
    <!-- Header -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
          {% if request.user.is_authenticated %}
              <p class="m-auto">Hello, {{request.user.username}}</p>
          {% endif %}
      </h5>
      {% if request.user.is_authenticated %}
        <div class="search-bar mt-sm-2 mr-2">
            <form method="get">
                <input class="form-control"  type="text" name="q" id="id_q" placeholder="Search...">
            </form>
        </div>
      {% endif %}
      <nav class="my-2 my-md-0 mr-md-3">
          {% if request.user.is_authenticated %}
              <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
              <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
            <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
        {% endif %}	
        
      </nav>
    </div>
    {% if request.user.is_authenticated %}

        <style>
            /* Style for the container */
            .image-container {
                width: 200px;
                height: 200px;
                border-radius: 50%; /* Makes it round */
                overflow: hidden; /* Hide overflowing parts of the image */
                border: 2px solid #ccc; /* Optional border */
            }

            /* Style for the image inside the container */
            .image-container img {
                width: 100%;
                height: 100%;
                object-fit: cover; /* Maintain aspect ratio and cover the container */
            }
        </style>
    </head>
    <body>
        <div class="image-container">
            <img src="{% static 'logo.jpg' %}" alt="Your Image">
        </div>
    </body>

    <style type="text/css">

      @media (max-width: 768px) { 
        .right-column{
          margin-left: 0px;
        }
      }
    
      @media (min-width: 768px) { 
        .right-column{
          margin-left: 20px;
        }
      }
    
      .blog-post-container{
        margin-bottom: 20px;
        width: 100%;
      }
      .create-post-bar{
        background-color: #fff;
        margin-bottom:20px;
      }
    
      .left-column{
        padding:0px;
      }
    
      .right-column{
        padding:0px;
      }
      .lead{
        font-size: 17px;
      }
      .blog-posts{
        max-width: 500px;
        width: 100%;
        margin: auto;
        
      }
    </style>
    
    
    
    <div class="container mt-4 p-4">
      <div class="row">
        <div class="blog-posts" style="margin-top: 70px;">
          <h3 class="mb-3 font-weight-normal">Products</h3>
          {% if blog_posts %}
          <ul>
            {% for post in blog_posts %}
              <a href="{% url 'org:detail' post.slug %}" style="text-decoration: none;">
                <li class="list-group-item">{{post}}</li>
              </a>
            {% endfor %}
            <a href="{% url 'org:create' %}" style="margin-left: 340px;">Add Product...</a>
          </ul>
          {% else %}
            <p>You have no products. Create a product <a href="{% url 'org:create' %}">here</a>.</p>
          {% endif %}
        </div>
      </div>
    </div>





    {% else %}






        <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    
        <style>
          .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }
    
          @media (min-width: 768px) {
            .bd-placeholder-img-lg {
              font-size: 3.5rem;
            }
          }
        </style>
    
        
        <!-- Custom styles for this template -->
        <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="blog.css" rel="stylesheet">
      </head>
      <body>
    <main class="container">
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 fst-italic">View, manage and analyse company's recent and past products for neccessary reviews and statistics.</h1>
          <p class="lead my-3"></p>
          <p class="lead mb-0"><a href="{% url 'register' %}" class="text-white fw-bold">Register your organisation now !!</a></p>
        </div>
      </div>
    
      <div class="row mb-2">
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">D.S</strong>
              <h3 class="mb-0">Featured post</h3>
              <p class="card-text mb-auto">Venture into an improved means of data analysis and survey.</p>
              <a href="{% url 'register' %}" class="stretched-link">Register...</a>
            </div>
            <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"> <image x="0" y="0" width="200" height="200" xlink:href="{% static 'logo.jpg' %}" /></svg>
    
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-success">D.S</strong>
              <h3 class="mb-0">Post title</h3>
              <p class="mb-auto">Keep your organisation's account updated by adding new products description to your profile.</p>
              <a href="{% url 'login' %}" class="stretched-link">Login...</a>
            </div>
            <div class="col-auto d-none d-lg-block">
              <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"> <image x="0" y="0" width="200" height="200" xlink:href="{% static 'logo4.jpg' %}" /></svg>
    
            </div>
          </div>
        </div>
      </div>


    {% endif %}
    <!-- End Header -->
    
    <script type="text/javascript">
        document.getElementById("id_q").value = "{{query}}"
    </script>
	
</div>
<!-- End Body -->


</body>


</html>