src/org/urls.py
from django.urls import path
from org.views import (
	create_org_view,
	detail_org_view,
	edit_org_view,
)

app_name = 'org'

urlpatterns = [
    path('create/', create_org_view, name="create"),
    path('<slug>/', detail_org_view, name="detail"),
    path('<slug>/edit/', edit_org_view, name="edit"),
 ]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from post.views import (
	home_view,
)

from home.views import (
    registration_view,
    logout_view,
    login_view,
	
)

urlpatterns = [
    path('', home_view, name="home"),
    path('org/', include('org.urls', 'org')),
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/org/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save 
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_delete

def upload_location(instance, filename):
    file_path = 'org/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

class Product(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(max_length=5000, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='date updated')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
    
@receiver(post_delete, sender=Product)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    
    
def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug=slugify(instance.author.username + '-' + instance.title)
        
pre_save.connect(pre_save_product_receiver, sender=Product)
    

src/org/forms.py
from django import forms

from org.models import Product 


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = Product
		fields = ['title', 'description', 'price', 'image']


class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = Product
		fields = ['title', 'description', 'price', 'image']

	def save(self, commit=True):
		org_post = self.instance
		org_post.title = self.cleaned_data['title']
		org_post.description = self.cleaned_data['description']
		org_post.price = self.cleaned_data['price']
		
        
		if self.cleaned_data['image']:
			org_post.image = self.cleaned_data['image']

		if commit:
			org_post.save()
		return org_post

src/org/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from org.models import Product
from org.forms import CreateBlogPostForm, UpdateBlogPostForm
from home.models import Account


def create_org_view(request):
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()

	context['form'] = form

	return render(request, "org/create_org.html", {})
    

	


def detail_org_view(request, slug):

	context = {}

	org_post = get_object_or_404(Product, slug=slug)
	context['org_post'] = org_post

	return render(request, 'org/detail_org.html', context)



def edit_org_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	org_post = get_object_or_404(Product, slug=slug)

	if org_post.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=org_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			org_post = obj

	form = UpdateOrgPostForm(
			initial = {
					"title": org_post.title,
					"description": org_post.description,
					"price": org_post.price,
					"image": org_post.image,
			}
		)

	context['form'] = form
	return render(request, 'org/edit_org.html', context)


def get_org_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = Product.objects.filter(
				Q(title__icontains=q) | 
				Q(description__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))

src/org/templates/org/create_org.html
<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>

<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}
	.submit-button{
		max-width: 200px;
	}
</style>


<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data"> {% csrf_token %}
				
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<div class="form-group">
					<label for="id_description">Description</label>
					<textarea class="form-control" rows="10" type="text" name="description" id="id_description" placeholder="About the product..." required></textarea>
				</div>

				<div class="form-group">
					<label for="id_price">Price</label>
					<input type="decimal" name="price" class="form-control" id="id_price" placeholder="Price" required>
				</div>

				<div class="form-group">
					<label for="id_image">Image</label>
					<input type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Save</button>
			</form>
		</div>
	</div>
</div>

</body>


</html>

src/org/templates/org/detail_org.html
<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>

<style type="text/css">
	.card {
		max-width: 700px;
	}
	.container {
		padding: 20px;
	}
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>


<div class="container">
	<div class="row">
		
		<div class="card m-auto">
			<img class="card-img-top" src="{{org_post.image.url}}">
			<div class="card-body my-2">
				<h2 class="card-title">{{org_post.title}}</h2>
				<h1 class="card-text">{{org_post.description|safe}}</h1>
				<p class="card-text">{{org_post.price}}</p>
				
			</div>
			<div class="card-footer text-muted">
				Updated on {{org_post.date_updated}} by {{org_post.author}}
			</div>
		</div>
	</div>
</div>

</body>


</html>

src/org/templates/org/edit_org.html
<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>

<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
			
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_description">Description</label>
					<textarea class="form-control" rows="10" type="text" name="description" id="id_description" value="{{form.initial.description}}"></textarea>
				</div>

				<div class="form-group">
					<label for="id_price">Price</label>
					<input class="form-control" type="decimal" name="price" id="id_price" placeholder="Price" value="{{form.initial.price}}" autofocus>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>
</body>


</html>